[bilastine]
brand_names = ["Blexten"]
cost = [{ province = "ON", price = "~$1 CAD per 20mg tab" }]
moa = "H1 antagonist. Marketed as limited CNS distribution."
half_life = "~15 hours"
routes = "oral tab, liquid (uncommon)"
doses = [
  { indication = "CSU, AR", dose = "20mg daily to QID", notes = "adult dosing" },
  { indication = "CSU, AR", dose = "10mg daily to QID", notes = "pediatric dosing" },
]
age_group = ">=12 years of age; has been used off-label in younger children"
pregnancy = "Avoid (not enough data)"
contraindications = "Hypersensitivity, QT prolongation or history of torsades"
side_effects.common = "QT prolongation; drowsiness (4%); headache (4%). For reference, drowisness/headache had a 2% incidence rate in placebo arm"
side_effects.severe = "Torsades (very rare)"
monograph_links = ["https://pdf.hres.ca/dpd_pm/00062419.PDF"]

[loratadine]
brand_names = ["Claritin", "Alavert"]
cost = [{ province = "ON", price = "~$0.50 CAD per 10mg tab" }]
moa = "H1 antagonist with minimal CNS penetration."
half_life = "~8 hours (active metabolite ~27 hours)"
routes = "oral tab, liquid, disintegrating tab"
doses = [
  { indication = "AR, CSU", dose = "10mg once daily", notes = "adult dosing" },
  { indication = "AR, CSU", dose = "5mg once daily", notes = "pediatric dosing (ages 2-5)" },
]
age_group = ">=2 years of age"
pregnancy = "Considered safe (Category B)"
contraindications = "Hypersensitivity to loratadine or desloratadine"
side_effects.common = "Headache, dry mouth, fatigue (~2-3%)"
side_effects.severe = "Rare anaphylaxis, hepatic dysfunction"
monograph_links = ["https://example.com/loratadine-monograph"]

[fexofenadine]
brand_names = ["Allegra", "Telfast"]
cost = [{ province = "ON", price = "~$1.20 CAD per 180mg tab" }]
moa = "H1 antagonist. Non-sedating antihistamine."
half_life = "~14 hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "AR, CSU", dose = "180mg once daily", notes = "adult dosing" },
  { indication = "AR, CSU", dose = "30mg twice daily", notes = "pediatric dosing (ages 2-11)" },
]
age_group = ">=2 years of age"
pregnancy = "Considered safe (Category B)"
contraindications = "Hypersensitivity to fexofenadine"
side_effects.common = "Headache (~1%), dizziness (<1%)"
side_effects.severe = "Rare hypersensitivity reactions"
monograph_links = ["https://example.com/fexofenadine-monograph"]
